#!/bin/sh
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

destination="${1}"

if [[ -z "${destination}" ]]; then
  echo "usage: ${0} <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:${PATH}

payload="$(mktemp /tmp/resource-in.XXXXXX)"

cat > ${payload} <&0

filename="$(cat ${payload} | jq -r '.source.filename')"
content="$(cat ${payload} | jq -r '.source.content')"

echo "${content}" > ${destination}/${filename}

echo '{"version": {"version": "1"}}' 1>&3
